package storage

import (
 "context"; "encoding/json"; "errors"; "fmt"; "time"
 "github.com/jackc/pgx/v5/pgxpool"
 "github.com/flowpilot/flowpilot/internal/domain"
)
type Store struct { Pool *pgxpool.Pool }
func Open(ctx context.Context, url string)(*Store,error){ p,e:=pgxpool.New(ctx,url);if e!=nil{return nil,e};return &Store{p},p.Ping(ctx) }
func (s *Store) CreateWorkflow(c context.Context,n,d string)(domain.Workflow,error){ var w domain.Workflow; row:=s.Pool.QueryRow(c,`INSERT INTO workflows(name,description) VALUES($1,$2) RETURNING id,name,description,status,draft,draft_revision,published_version,created_at,updated_at`,n,d); e:=row.Scan(&w.ID,&w.Name,&w.Description,&w.Status,graph(&w.Draft),&w.DraftRevision,&w.PublishedVersion,&w.CreatedAt,&w.UpdatedAt);return w,e }
func graph(g *domain.Graph) any{return (*jsonGraph)(g)}
type jsonGraph domain.Graph
func (g *jsonGraph) Scan(src any) error{var data []byte;switch value:=src.(type){case []byte:data=value;case string:data=[]byte(value);default:return fmt.Errorf("unsupported graph value type %T",src)};return json.Unmarshal(data,(*domain.Graph)(g))}
func (s *Store) ListWorkflows(c context.Context)([]domain.Workflow,error){ rows,e:=s.Pool.Query(c,`SELECT id,name,description,status,draft,draft_revision,published_version,created_at,updated_at FROM workflows ORDER BY updated_at DESC`);if e!=nil{return nil,e};defer rows.Close(); out:=[]domain.Workflow{};for rows.Next(){var w domain.Workflow;e=rows.Scan(&w.ID,&w.Name,&w.Description,&w.Status,graph(&w.Draft),&w.DraftRevision,&w.PublishedVersion,&w.CreatedAt,&w.UpdatedAt);if e!=nil{return nil,e};out=append(out,w)};return out,rows.Err() }
func (s *Store) UpdateDraft(c context.Context,id string, revision int64,g domain.Graph)(domain.Workflow,error){ b,_:=json.Marshal(g);var w domain.Workflow;r:=s.Pool.QueryRow(c,`UPDATE workflows SET draft=$1,draft_revision=draft_revision+1,updated_at=now() WHERE id=$2 AND draft_revision=$3 RETURNING id,name,description,status,draft,draft_revision,published_version,created_at,updated_at`,b,id,revision);e:=r.Scan(&w.ID,&w.Name,&w.Description,&w.Status,graph(&w.Draft),&w.DraftRevision,&w.PublishedVersion,&w.CreatedAt,&w.UpdatedAt);return w,e }
func (s *Store) Publish(c context.Context,id string)(domain.Workflow,error){ tx,e:=s.Pool.Begin(c);if e!=nil{return domain.Workflow{},e};defer tx.Rollback(c);var w domain.Workflow; e=tx.QueryRow(c,`SELECT id,name,description,status,draft,draft_revision,published_version,created_at,updated_at FROM workflows WHERE id=$1 FOR UPDATE`,id).Scan(&w.ID,&w.Name,&w.Description,&w.Status,graph(&w.Draft),&w.DraftRevision,&w.PublishedVersion,&w.CreatedAt,&w.UpdatedAt);if e!=nil{return w,e};v:=1;if w.PublishedVersion!=nil{v=*w.PublishedVersion+1};b,_:=json.Marshal(w.Draft);_,e=tx.Exec(c,`INSERT INTO workflow_versions(workflow_id,version,definition) VALUES($1,$2,$3)`,id,v,b);if e!=nil{return w,e};e=tx.QueryRow(c,`UPDATE workflows SET published_version=$1,status='ACTIVE',updated_at=now() WHERE id=$2 RETURNING id,name,description,status,draft,draft_revision,published_version,created_at,updated_at`,v,id).Scan(&w.ID,&w.Name,&w.Description,&w.Status,graph(&w.Draft),&w.DraftRevision,&w.PublishedVersion,&w.CreatedAt,&w.UpdatedAt);if e!=nil{return w,e};return w,tx.Commit(c) }
func (s *Store) Start(c context.Context,wf string,input map[string]any)(domain.Execution,error){ b,_:=json.Marshal(input);var x domain.Execution;e:=s.Pool.QueryRow(c,`WITH w AS (SELECT id,published_version FROM workflows WHERE id=$1 AND status='ACTIVE') INSERT INTO executions(workflow_id,workflow_version,trigger_type,input) SELECT id,published_version,'manual',$2 FROM w RETURNING id,workflow_id,workflow_version,trigger_type,status,input,created_at,started_at,finished_at`,wf,b).Scan(&x.ID,&x.WorkflowID,&x.WorkflowVersion,&x.TriggerType,&x.Status,&x.Input,&x.CreatedAt,&x.StartedAt,&x.FinishedAt);if e!=nil{return x,e};_,e=s.Pool.Exec(c,`INSERT INTO durable_jobs(execution_id) VALUES($1)`,x.ID);return x,e }
func (s *Store) StartWebhook(c context.Context, hook string, input map[string]any) (domain.Execution, error) {
	rows, err := s.Pool.Query(c, `SELECT w.id,v.definition FROM workflows w JOIN workflow_versions v ON v.workflow_id=w.id AND v.version=w.published_version WHERE w.status='ACTIVE'`)
	if err != nil { return domain.Execution{}, err }; defer rows.Close()
	for rows.Next() { var workflowID string; var definition domain.Graph; if err=rows.Scan(&workflowID, graph(&definition)); err != nil { return domain.Execution{},err }; for _, node := range definition.Nodes { if node.Type == "webhook_trigger" && fmt.Sprint(node.Config["webhookId"]) == hook { return s.start(c, workflowID, "webhook", input) } } }
	return domain.Execution{}, errors.New("webhook not found")
}
func (s *Store) start(c context.Context, workflowID, trigger string, input map[string]any) (domain.Execution,error) { b,_:=json.Marshal(input); var x domain.Execution; err:=s.Pool.QueryRow(c,`WITH w AS (SELECT id,published_version FROM workflows WHERE id=$1 AND status='ACTIVE') INSERT INTO executions(workflow_id,workflow_version,trigger_type,input) SELECT id,published_version,$2,$3 FROM w RETURNING id,workflow_id,workflow_version,trigger_type,status,input,created_at,started_at,finished_at`,workflowID,trigger,b).Scan(&x.ID,&x.WorkflowID,&x.WorkflowVersion,&x.TriggerType,&x.Status,&x.Input,&x.CreatedAt,&x.StartedAt,&x.FinishedAt); if err!=nil{return x,err}; _,err=s.Pool.Exec(c,`INSERT INTO durable_jobs(execution_id) VALUES($1)`,x.ID);return x,err }
func (s *Store) ListExecutions(c context.Context,wf ...string)([]domain.Execution,error){if len(wf)==0{return []domain.Execution{},nil};rows,e:=s.Pool.Query(c,`SELECT id,workflow_id,workflow_version,trigger_type,status,input,result,error,created_at,started_at,finished_at FROM executions WHERE workflow_id=$1 ORDER BY created_at DESC LIMIT 100`,wf[0]);if e!=nil{return nil,e};defer rows.Close();out:=[]domain.Execution{};for rows.Next(){var x domain.Execution;e=rows.Scan(&x.ID,&x.WorkflowID,&x.WorkflowVersion,&x.TriggerType,&x.Status,&x.Input,&x.Result,&x.Error,&x.CreatedAt,&x.StartedAt,&x.FinishedAt);if e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}
func (s *Store) Cancel(c context.Context,id string) error { tag,e:=s.Pool.Exec(c,`UPDATE executions SET status='CANCELLED',cancelled_at=now(),finished_at=now() WHERE id=$1 AND status IN ('QUEUED','STARTING','RUNNING','WAITING','RETRYING')`,id);if e==nil&&tag.RowsAffected()==0{return errors.New("execution cannot be cancelled")};return e }
func (s *Store) Claim(c context.Context,worker string)(string,error){var id string;e:=s.Pool.QueryRow(c,`WITH candidate AS (SELECT id FROM durable_jobs WHERE done_at IS NULL AND run_at<=now() AND (lease_until IS NULL OR lease_until<now()) ORDER BY run_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE durable_jobs j SET worker_id=$1,lease_until=now()+interval '30 seconds',attempts=attempts+1 FROM candidate WHERE j.id=candidate.id RETURNING j.execution_id`,worker).Scan(&id);return id,e}
func (s *Store) Finish(c context.Context,id string,result any,fail error)error{b,_:=json.Marshal(result);state:="SUCCEEDED";var msg any=nil;if fail!=nil{state="FAILED";msg=fail.Error()};_,e:=s.Pool.Exec(c,`UPDATE executions SET status=$2,result=$3,error=$4,started_at=COALESCE(started_at,now()),finished_at=now() WHERE id=$1`,id,state,b,msg);if e!=nil{return e};_,e=s.Pool.Exec(c,`UPDATE durable_jobs SET done_at=now() WHERE execution_id=$1`,id);return e}
func (s *Store) LoadExecutionGraph(c context.Context,id string)(domain.Graph,map[string]any,error){var g domain.Graph;var input map[string]any;e:=s.Pool.QueryRow(c,`SELECT v.definition,e.input FROM executions e JOIN workflow_versions v ON v.workflow_id=e.workflow_id AND v.version=e.workflow_version WHERE e.id=$1`,id).Scan(graph(&g),&input);return g,input,e}
func (s *Store) Event(c context.Context,id,node,kind string,payload map[string]any){b,_:=json.Marshal(payload);_,_ = s.Pool.Exec(c,`INSERT INTO execution_events(execution_id,node_id,type,payload) VALUES($1,$2,$3,$4)`,id,node,kind,b)}
func (s *Store) Close(){s.Pool.Close()}; var _=time.Second
